### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gamehelp16** [mjbrownie/hackertyper.vim#1]
I'm sorry if this is a noob question, but I don't quite understand how to use this plugin(?). I have done the installation using the code given from the readme file but I don't understand the first step of the "usage" part. Also, commands like :WriteHackerTyper don't seem to exist yet even after installing.

**Comment by mjbrownie** [comment]
Hello,

Just remember this plugin is for amusement only. 

The installation instructions assumed some knowledge of a vim plugin manager such as pathogen or vundle which isn't installed by default. I'll fix this.

some discussion here.

http://vi.stackexchange.com/questions/388/what-is-the-difference-between-the-vim-plugin-managers 

Perhaps you should look at vim-plug as it is a newer/better alternative. 

https://github.com/junegunn/vim-plug

call plug#begin('~/.vim/plugged')
Plug 'mjbrownie/hackertyper'
call plug#end()

**Comment by gamehelp16** [comment]
> Just remember this plugin is for amusement only.

Of course I will remember ;)

So I already have vundle installed so I installed this plugin with it. I didn't know that you can just install this using existing plugin managers (I'm a noob hehe). Thank you for your answer,
